### PR TITLE
Hide splash page when app frame is active

### LINKED ISSUE #435: Agent Frame sometimes interferes with test Frame
Depending on the CSS of the app under test, the agent frame doesn't play nicely with it:

BigTest agent clobbering application frame

### PR DESCRIPTION
**Pull request by jnicklas**
Closes #435

### CODE REVIEW

**Review by cowboyd — COMMENTED** [review]
How does this even work? Will it work on a dark themed desktop?

**Comment by jnicklas** [comment]
The iframe is always in front of the splash page. The problem only occurs when the app does not have a background color on its body, so the frame shows through the page. By adding a background color to the iframe we simply paint over it ;) The default background color in browsers is always white as far as I know, so it does look correct, regardless of nightmode or not.

**Comment by jnicklas** [comment]
And the iframe does not initially have a `src` attribute, so the splash page is still shown before we visit the first time.

**Review by cowboyd — APPROVED** [review]
👍

**Pull request merged**
