### PR TITLE
Bump chromedriver/geckodriver versions

### PR DESCRIPTION
**Pull request by jnicklas**
And down constrain them upwards, most likely we want these to be freely upgradeable.

### CODE REVIEW

**Review by cowboyd — APPROVED** [review]

**Comment by cowboyd** [comment]
🤣 looks like the chrome version is 87 on ubuntu, but still 86 on windows

**Comment by jnicklas** [comment]
> 🤣 looks like the chrome version is 87 on ubuntu, but still 86 on windows

Ugh.... So what do we do here?

**Comment by cowboyd** [comment]
> Ugh.... So what do we do here?

It sounds like this is a bug in the virtual environments https://github.com/actions/virtual-environments/issues/1275 since if I read correctly, they should release with the latest version of chrome weekly. The fact that 87 was not picked up on windows would indicate that something didn't go quite right wit their image builder.

We can either wait for that fix, or maybe we can run an installer on the windows environment, or use a custom image? @jbolda do you have any experience using custom windows images on github actions?

**Comment by jbolda** [comment]
I haven't tried to use a custom image at all, but I imagine that isn't a great long term solution? Particularly when considering that Github Actions seems to be the low bar in terms of setting up CI/CD, and we don't want to turn people away with a complicated setup for bigtest.

I assume since we are switching to `>=` that bigtest doesn't _really care_ about the exact version, just that it works and the user has whatever version that they need for their feature set (which most of the time probably doesn't matter either). In userland, they will install and get a version in their lockfile. On CI though, I wonder if we (internally and for users) push towards [using the system chromedriver](https://github.com/giggio/node-chromedriver#skipping-chromedriver-download) which should also be compatible with the system chrome.

**Comment by cowboyd** [comment]
> I haven't tried to use a custom image at all, but I imagine that isn't a great long term solution? Particularly when considering that Github Actions seems to be the low bar in terms of setting up CI/CD, and we don't want to turn people away with a complicated setup for bigtest.
> 
> I assume since we are switching to `>=` that bigtest doesn't _really care_ about the exact version, just that it works and the user has whatever version that they need for their feature set (which most of the time probably doesn't matter either). In userland, they will install and get a version in their lockfile. On CI though, I wonder if we (internally and for users) push towards [using the system chromedriver](https://github.com/giggio/node-chromedriver#skipping-chromedriver-download) which should also be compatible with the system chrome.

@jbolda This isn't so much for people using bigtest in their own CI, but only for our CI. I think that the solution is that we will end up having people use _remote_ webdrivers that are running in an image. So, for example, we would say recommend that you use one of the public webdriver images in your CI and use it as a service. However, this isn't an option for us, because we actually need to unit test the _local_ webdrivers in CI which in the longer term will only really be used in development.

**Comment by cowboyd** [comment]
@jbolda I think the best option is your suggestion to use the system chromedriver if we can

**Comment by jbolda** [comment]
May have the added benefit of speeding up test runs too.

**Comment by cowboyd** [comment]
Well, looks like in the intervening time, they updated the windows image. Until next time we see you chromedriver update bug!

🥫🏃🏻‍♂️ 

(although we should still use the system chromedriver at some point)

**Pull request merged**
