### PR TITLE
New landing page Oct 2020

### PR DESCRIPTION
**Pull request by jorgelainfiesta**
## Approach:

- The landing page was generated via Webflow, using styles from Frontside's website.
- We use a slightly custom build of asciinema, with heavy work on the styles. 
- My idea is to publish the static pages, and leave Gatsby out for the time being. 

## Pending

- [x] Define title
- [x] Get a quote to use instead of Warren's
- [x] Set up Welcome email on mailchimp
- [x] Resolve `https://legacy.bigtest.io` to `bigtest.io/legacy` through Netlify's rewrites
- [x] Forward traffic from `v1.bigtest.io` to `bigtest.io/legacy` (through dnsimple?)

### CODE REVIEW

**Comment by jnicklas** [comment]
@jorgelainfiesta can we see the result anywhere?

**Comment by taras** [comment]
@jnicklas there is a link in checks called: `netlify/bigtest/deploy-preview`. Click on Details. (it just became visible now)

**Comment by cowboyd** [comment]
@jorgelainfiesta something is wonky about the first screen recording... Is there an online editor or something that we can use with it?

**Comment by jnicklas** [comment]
Is there any way of avoiding the line breaks in the recording? They don't look so nice:

Screenshot 2020-10-29 at 13 19 58

Screenshot 2020-10-29 at 13 20 13

**Comment by cowboyd** [comment]
@jnicklas It's just an svg file, so it should be just either a css feature to turn on word wrap? I'm not sure how svg styles work though. @jorgelainfiesta?

**Comment by taras** [comment]
image

It looks like the svg outputs the result of the capture, so you might need to re-record with a wider screen and then reside the video with css.

**Comment by jorgelainfiesta** [comment]
There's no svgs involved I'm afraid. it's all generated text. I've made adjustments by manually cutting down pieces, I'll do that for the two specific lines that you mention.

**Comment by jorgelainfiesta** [comment]
Having the legacy website under `/legacy` required too much work so we opted to keep it on `https://legacy.bigtestjs.io`. Additionally, we addressed the `v1` problem by setting up an SSL for the subdomain such that it could redirect to the `legacy` subdomain.

**Review by cowboyd — APPROVED** [review]
This looks great to me from a copy perspective 👍

**Pull request merged**
