### PR TITLE
Fix race condition in chromedriver

### PR DESCRIPTION
**Pull request by jnicklas**
Making an attempt to fix this.

### CODE REVIEW

**Comment by cowboyd** [comment]
@jnicklas maybe disentangle the chromedriver upgrade which is failing on windows, so we can get this one through?

**Comment by jnicklas** [comment]
Locally this seems to improve things for me, but I think we really need to release this and upgrade bigtest on cvex to see whether it actually works.

**Review by cowboyd — COMMENTED** [review]
What if we just removed the exterior timeout entirely? We only have two times we use this, in our mocha tets, and in our CLI, both of which are subject to external timeouts. 

Internally, we would still have an iteration timeout that had a linear backoff or something.

If we leave the timeout in here, we're just moving the booby trap from one corner of the room into another.

**Comment by cowboyd** [comment]
This also would make it compatible with a higher order operation whose only puprose is to timebox something. Operations with implicit timeouts are inherently un-composable.

**Comment by jnicklas** [comment]
@cowboyd I think that's a good idea. I've removed the global timeout, but kept the per-request timeout. Since that timeout is caught, it shouldn't bubble up and cause a failure, it will only cause the request to abort and be retried, which is what we want to do to make the startup as fast as possible.

**Review by cowboyd — APPROVED** [review]

**Pull request merged**
