### PR TITLE
Platform styles

### PR DESCRIPTION
**Pull request by jorgelainfiesta**
## Motivation

Create a consistent look for the platform section.

## Approach

- I created a redirect from the index to `/interactors`, so it's our default page at the moment
- The platform page is a refried version of what we currently have. 
- I have a made up example on the platform landing page, is that how an error could look like? @cowboyd 
- I moved the architecture pieces that we had to `/docs/platform/architecture`. 

## Questions

1. Do we want to add more pieces now or are we ok with Agents + GraphQL?
2. Now the website doesn't have any subscription form. My idea was to focus on having people join Discord, and leverage a welcome bot there to engage people and suggest them to sign up to a newsletter if they're interested. But I don't know if that's a good route or if we should anyways have a sign up box somewhere. I'd also like to experiment with adding a bot to the website to collect feedback and invite people to join discord/newsletter.

[Preview here](https://deploy-preview-724--bigtest.netlify.app/bigtest/platform)

### CODE REVIEW

**Review by minkimcello — CHANGES_REQUESTED** [review]
Jen made improvements to the platform docs so you'll need to rebase first

**Comment by jorgelainfiesta** [comment]
@minkimcello done 👍

**Comment by minkimcello** [comment]
Screen Shot 2020-12-11 at 9 29 35 AM

@jorgelainfiesta Did you rebase with v0? You need to rebase with init-docusaurus

**Comment by jorgelainfiesta** [comment]
I did rebase to `init-docusaurus`, and refreshed that branch with what's on origin just now to make sure. I don't know what's going on. I just tried deleting my `init-docusaurus` branch to rebase it against a fresh copy idk.

**Review by minkimcello — APPROVED** [review]

**Pull request merged**
