### PR TITLE
Update README

### LINKED ISSUE #120: Better README
## Motivation

We're making big changes on BigTest. We've deprecated the old website, but there's still a lot of documentation missing to help people understand what's happening.

## Approach

Write a README for this repo in which we explain:

- What is going on at BigTest
- Why did we decide to do this change
- What can they do if they were using BigTest before
- What can they do for the new BigTest
- Subscribe to newsletter for new information when it's available

### LINKED ISSUE #135: Branded Readme
The original README was pretty awesome. We should consider branding it (in addition to having better content) https://github.com/thefrontside/bigtest/blob/f23bd617835ef0a12a896894ad5c7530ba907469/README.md

This is an addendum to #120

### PR DESCRIPTION
**Pull request by jnicklas**
[Rendered](https://github.com/thefrontside/bigtest/blob/readme-update/README.md)

Closes #120
Closes #135

### CODE REVIEW

**Comment by jnicklas** [comment]
I did a first stab at making a better README, based partly on the [old README](https://github.com/thefrontside/bigtest/blob/f23bd617835ef0a12a896894ad5c7530ba907469/README.md).

There are a number of things listed in #120 that we could mention in the README which we don't talk about yet, but I don't know how current these ideas are given that #120 was added all the way back in February.

**Comment by jnicklas** [comment]
I also think it would be good to add a rather prominent Frontside logo. Something like "a Frontside project" under the BigTest logo maybe?

**Comment by taras** [comment]
@jorgelainfiesta how should we highlight frontside in the readme?

**Review by taras — APPROVED** [review]
👍

**Review by cowboyd — APPROVED** [review]

**Pull request merged**
