### PR TITLE
Fix newsletter padding

### PR DESCRIPTION
**Pull request by jorgelainfiesta**
## Motivation

#855 

## Approach

Updated the CSS to have the newsletter form respond more smoothly to the window size.

Screenshot 2021-02-12 at 11 03 17

### CODE REVIEW

**Comment by minkimcello** [comment]
Screen Shot 2021-02-12 at 10 37 10 AM

The picture still gets cropped in full desktop mode and we're still missing the bottom padding.

And I believe you need to rebase because you're introducing todomvc package.json back

**Comment by jorgelainfiesta** [comment]
Thanks Min! should be good now

**Comment by minkimcello** [comment]
@jorgelainfiesta looks good. just _one_ more in the `about` page. i think the body needs a bottom padding/margin?

Screen Shot 2021-02-13 at 10 05 37 AM

versus

Screen Shot 2021-02-13 at 10 05 22 AM

**Comment by jorgelainfiesta** [comment]
Umm interesting, there's probably a break point that needs adjustment. I'll check it out, thanks.

Update: no, the problem is that that component is set within another component so the breakpoint is not working because it targets the window width... need some refactoring

**Review by minkimcello — APPROVED** [review]

**Pull request merged**
