### PR TITLE
Prepare for reporter API

### LINKED ISSUE #525: Display assertion errors
With #462, we added sweet and fresh error output that diagnosed exactly what was going on in steps, but we forgot to display the error output for assertions. Right now, when an assertion fails, we don't have any idea why.

We should add error display logic to our assertions as well.

### PR DESCRIPTION
**Pull request by jnicklas**
In #487, we proposed a reporter API for pluggable test result reporters. In order to get there, we'll need to do some cleanup work.

Closes #525 

Output looks like this:

Screenshot 2020-09-11 at 18 44 13

### CODE REVIEW

**Comment by jnicklas** [comment]
I found it really hard to pick good icons for the ok/failed/disregarded states. It was hard to find three characters which individually look good, also look good together, are easily distinguishable from each other, and convey their intended meaning. I ended up with `✓◦⨯`. A less unicode option may be to go with the traditional `.SE` which for example RSpec uses.

I also tried using `↪` for steps and `✓` for assertions in the progress line as well, but that looked very messy.

**Comment by RobbieTheWagner** [comment]
@jnicklas any particular reason for removing ololog and manually using `console.log`? Ololog provided a lot of nice things for us, handled indentions without manually calculating the spaces, etc.

**Comment by jnicklas** [comment]
@rwwagner90 I did not really feel that it was needed. ololog seems great, but it's also a huge library with many features. At this point in time we really only need colors (already provided by chalk), and indentation (trivial to implement ourselves), so it felt a bit overkill to me.

**Review by cowboyd — APPROVED** [review]
Looks great. 👍

**Comment by RobbieTheWagner** [comment]
@cowboyd @jnicklas I disagree with the removal of ololog. It handles so much for us without a lot of manual calculations like this. We lose a lot with manual console.log usage. We shouldn't care about the size of the library, since we're writing a testing framework here and not shipping bytes with people's apps. Really wish we could have discussed this more before merging, as I would love to simplify things and not rip out dependencies others are adding without talking about it.

**Pull request merged**
