### PR TITLE
Add hook to disable actions

### PR DESCRIPTION
**Pull request by jnicklas**
This adds a hook on the interactor library so we can disable actions, it remains to be solved how we hook this up into the runner.

### CODE REVIEW

**Comment by cowboyd** [comment]
Instead of making this a setting on interactor, what if interactors read state from the runner and adjusted behavior accordingly? That allows for more than one way to enforce which activities are acceptable during which phase.

**Comment by jnicklas** [comment]
Yeah, I'm thinking that this probably isn't the ideal way of doing this. I've converted this to draft for now and will try and revise it.

**Comment by jnicklas** [comment]
See also #315

**Comment by jnicklas** [comment]
Somehow this got accidentally merged 🤔 I removed the commit from the `new-interactors` branch, so this is no longer a part of #301

**Pull request merged**
